create database if not exists bookstore;

use bookstore;

drop table if exists Books;

/* This is the Books table.  It contains the master list of books
currently for sale.  The ISBN number is the primary key.  Some fields
are optional. */

/*Khalid notes: */
create table Books (
	isbn		char(14) unique not null primary key,
	title		char(80) not null,
	author		char(80) not null,
	subject		char(80) not null,
	pubyear		int(4),
	description	char(255),
	imageurl	char(128),
	quantity	int(6) not null,
	supplier	char(40),
	price		numeric(10,2) not null
);

drop table if exists Users;

/* This is the Users table.  It unifies customers and admins.
Observe that the credit card number and types can be null, since
some customers may not be comfortable with leaving their credit
card numbers on a system.  Also, why would employees (admins)
need to leave a credit card number? 

The password value is generated by a call to passwd_hash(), a 
built-in PHP function.  One never stores a plain text password. */

/*Khalid notes: is better to isolate admin from users for secuirty and foravid checking every user from db each time load page, and to make it easy for */
create table Users (
	username	char(16) unique not null primary key,
	lastname	char(30) not null,
	firstname	char(30) not null,
	address		char(50) not null,
	city		char(30) not null,
	state		char(2) not null,
	zip		int(5) not null,
    /*Khalid notes: telphone better be char to ovide crach program if user enter + or - */
	telephone	char(10) not null,
	email		char(128) not null,
    /*Khalid notes: ????? */
	passwdhash	char(60) not null, 
	cctype		char(1), 
	ccnumber	int(16),
	ccexpdate	int(6),
	isenabled	char(1)  /* Y or N */
);

drop table if exists Orders;

/* This is the Orders table, otherwise known as the shopping basket.
Since we do not currently have an order details table, only one item
can occupy the shopping basket at any one time.  This should be fixed. 
Value for order status: o=open, c=completed, x=cancelled */

/*Khalid notes: Forgien key are important to omake sure consisety.
for easy we will use same adress of user for deliver and in reality we will not need the address
 */
create table Orders (
	ordernumber	int(12) unique not null primary key,
	username	char(16) not null,
	orderisbn	char(14) not null,
	orderdate	int(8) not null,
	ordsecnum	int(4),
	orderstatus	char(1) not null, /* O, C, or X */
	orderqty	int(5) not null,
	ordertotal	numeric(8,2) not null
);

drop table if exists Cookies;

/* This is the Cookies table.  It stores the valid cookies that the
user needs to keep their identity infromation.  The cookiehash value
should be generated randomly to prevent someone from predicting sequential
value.  If the cookie is stale, it shouldn't be trusted.  */

create table Cookies (
	cookiehash	char(32) unique not null primary key,
	cookieuser	char(16) not null,
	cookiedate	int(8) not null,
	isstale		char(1)
);

drop table if exists Admins;

create table Admins (
    username  char(16) not null primary key,
    passwdhash char(60) not null
);